// this file was generated by gomacro command: import _i "github.com/steele232/zoumacro/cmd"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package cmd

import (
	r "reflect"
	"github.com/steele232/zoumacro/imports"
)

// reflection: allow interpreted code to import "github.com/steele232/zoumacro/cmd"
func init() {
	imports.Packages["github.com/steele232/zoumacro/cmd"] = imports.Package{
	Binds: map[string]r.Value{
		"New":	r.ValueOf(New),
	}, Types: map[string]r.Type{
		"Cmd":	r.TypeOf((*Cmd)(nil)).Elem(),
	}, 
	}
}
