// this file was generated by gomacro command: import _i "github.com/steele232/zoumacro/base/inspect"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package inspect

import (
	r "reflect"
	"github.com/steele232/zoumacro/imports"
)

// reflection: allow interpreted code to import "github.com/steele232/zoumacro/base/inspect"
func init() {
	imports.Packages["github.com/steele232/zoumacro/base/inspect"] = imports.Package{
	Types: map[string]r.Type{
		"Inspector":	r.TypeOf((*Inspector)(nil)).Elem(),
	}, 
	}
}
